#############################################################################
# Makefile for building: BehavePlus4
# Generated by qmake (1.07a) (Qt 3.3.3) on: Fri Oct 01 10:52:46 2004
# Project:  BehavePlus4.pro
# Template: app
# Command: $(QMAKE) -o qtmakefile BehavePlus4.pro
#############################################################################

####### Compiler, tools and options

CC		=	cl
CXX		=	cl
LEX		= flex
YACC		= byacc
CFLAGS	=	-nologo -Zm200 -W3 -MD -O1 -GX  -DUNICODE -DWIN32 -DQT_DLL -DQT_THREAD_SUPPORT -DQT_NO_DEBUG
CXXFLAGS	=	-nologo -Zm200 -W3 -w34100 -w34189 -MD -O1 -GX  -DUNICODE -DWIN32 -DQT_DLL -DQT_THREAD_SUPPORT -DQT_NO_DEBUG
LEXFLAGS	=
YACCFLAGS	=-d
QTVER = 3.3.3
QTDIR = C:\Qt\$(QTVER)
INCPATH	=	 -I"$(QTDIR)\include" -I"C:\Documents and Settings\cbevins\software\BehavePlus\v3\src" -I"C:\qt\3.3.3\mkspecs\win32-msvc.net"
LINK	=	link
LFLAGS	=	/NOLOGO /DELAYLOAD:comdlg32.dll /DELAYLOAD:oleaut32.dll /DELAYLOAD:winmm.dll /DELAYLOAD:wsock32.dll /DELAYLOAD:winspool.dll /SUBSYSTEM:WINDOWS /LIBPATH:"$(QTDIR)\lib"
LIBS	=	 "qt-mt333.lib" "qtmain.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "imm32.lib" "winmm.lib" "wsock32.lib" "winspool.lib" "delayimp.lib" "BehavePlus4.res" "opengl32.lib" "glu32.lib"
MOC		=	$(QTDIR)\bin\moc.exe
UIC		=	$(QTDIR)\bin\uic.exe
QMAKE		=	qmake
IDC		=	$(QTDIR)\bin\idc.exe
IDL		=	midl
ZIP		=	zip -r -9
COPY_FILE	=       copy
COPY_DIR	=       copy
DEL_FILE	=       del
DEL_DIR	=       rmdir
MOVE		=       move
CHK_DIR_EXISTS =	if not exist
MKDIR		=	mkdir
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)

####### Files

HEADERS =	aboutdialog.h \
		appdialog.h \
		appearancedialog.h \
		appfilesystem.h \
		app.h \
		appmessage.h \
		appproperty.h \
		appsiunits.h \
		apptranslator.h \
		appwindow.h \
		attachdialog.h \
		bpdocentry.h \
		bpdocument.h \
		calendardocument.h \
		cdtlib.h \
		composer.h \
		conflictdialog.h \
		contain.h \
		datetime.h \
		docdevicesize.h \
		docpagesize.h \
		docscrollview.h \
		doctabs.h \
		document.h \
		fdfmcdialog.h \
		fileselector.h \
		filesystem.h \
		fuelexportdialog.h \
		fuelinitdialog.h \
		fuelmodel.h \
		fuelwizards.h \
		globalposition.h \
		globalsite.h \
		graphaxle.h \
		graphbar.h \
		graph.h \
		graphlimitsdialog.h \
		graphline.h \
		graphmarker.h \
		guidedialog.h \
		helpbrowser.h \
        horizontaldistancedialog.h \
        humiditydialog.h \
		module.h \
		modulesdialog.h \
		moisscenario.h \
		newext.h \
		pagemenudialog.h \
		parser.h \
		platform.h \
		printer.h \
		propertydialog.h \
		property.h \
		randfuel.h \
		randthread.h \
		realspinbox.h \
		requestdialog.h \
		rundialog.h \
		rxvar.h \
		siunits.h \
		standardwizards.h \
		sundialog.h \
		sunview.h \
		textviewdocument.h \
		textview.h \
		toc.h \
		unitsconverterdialog.h \
		unitseditdialog.h \
		varcheckbox.h \
		wizarddialog.h \
		xeqapp.h \
		xeqappparser.h \
		xeqcalc.h \
		xeqfile.h \
		xeqtree.h \
		xeqtreeparser.h \
		xeqvar.h \
		xeqvaritem.h \
		xfblib.h \
		xmlparser.h
SOURCES =	cdtlib.c \
		aboutdialog.cpp \
		appdialog.cpp \
		appearancedialog.cpp \
		appfilesystem.cpp \
		appmessage.cpp \
		appproperty.cpp \
		appsiunits.cpp \
		apptranslator.cpp \
		appwindow.cpp \
		attachdialog.cpp \
		BehavePlus4.cpp \
		bpcomposecontaindiagram.cpp \
		bpcomposedoc.cpp \
		bpcomposefiredirdiagram.cpp \
		bpcomposefireshapediagram.cpp \
		bpcomposegraphs.cpp \
		bpcomposehaulingchart.cpp \
		bpcomposelogo.cpp \
		bpcomposepage.cpp \
		bpcomposetable1.cpp \
		bpcomposetable2.cpp \
		bpcomposetable3.cpp \
		bpcomposeworksheet.cpp \
		bpdocentry.cpp \
		bpdocument.cpp \
		bpfile.cpp \
		calendardocument.cpp \
		composer.cpp \
		conflictdialog.cpp \
		contain.cpp \
		datetime.cpp \
		docdevicesize.cpp \
		docpagesize.cpp \
		docscrollview.cpp \
		doctabs.cpp \
		document.cpp \
		fdfmcdialog.cpp \
		fileselector.cpp \
		filesystem.cpp \
		fuelexportdialog.cpp \
		fuelinitdialog.cpp \
		fuelmodel.cpp \
		fuelwizards.cpp \
		globalposition.cpp \
		globalsite.cpp \
		graphaxle.cpp \
		graphbar.cpp \
		graph.cpp \
		graphlimitsdialog.cpp \
		graphline.cpp \
		graphmarker.cpp \
		guidedialog.cpp \
		helpbrowser.cpp \
        horizontaldistancedialog.cpp \
        humiditydialog.cpp \
		module.cpp \
		modulesdialog.cpp \
		moisscenario.cpp \
		newext.cpp \
		pagemenudialog.cpp \
		parser.cpp \
		platform-windows.cpp \
		printer.cpp \
		property.cpp \
		propertydialog.cpp \
		randfuel.cpp \
		randthread.cpp \
		realspinbox.cpp \
		requestdialog.cpp \
		rundialog.cpp \
		rxvar.cpp \
		siunits.cpp \
		standardwizards.cpp \
		sundialog.cpp \
		sunview.cpp \
		textview.cpp \
		textviewdocument.cpp \
		toc.cpp \
		unitsconverterdialog.cpp \
		unitseditdialog.cpp \
		varcheckbox.cpp \
		wizarddialog.cpp \
		xeqapp.cpp \
		xeqappparser.cpp \
		xeqcalc.cpp \
		xeqcalcmask.cpp \
		xeqcalcreconfig.cpp \
		xeqfile.cpp \
		xeqtree.cpp \
		xeqtreeparser.cpp \
		xeqtreeprint.cpp \
		xeqvar.cpp \
		xeqvaritem.cpp \
		xfblib.cpp \
		xmlparser.cpp
OBJECTS =	cdtlib.obj \
		aboutdialog.obj \
		appdialog.obj \
		appearancedialog.obj \
		appfilesystem.obj \
		appmessage.obj \
		appproperty.obj \
		appsiunits.obj \
		apptranslator.obj \
		appwindow.obj \
		attachdialog.obj \
		BehavePlus4.obj \
		bpcomposecontaindiagram.obj \
		bpcomposedoc.obj \
		bpcomposefiredirdiagram.obj \
		bpcomposefireshapediagram.obj \
		bpcomposegraphs.obj \
		bpcomposehaulingchart.obj \
		bpcomposelogo.obj \
		bpcomposepage.obj \
		bpcomposetable1.obj \
		bpcomposetable2.obj \
		bpcomposetable3.obj \
		bpcomposeworksheet.obj \
		bpdocentry.obj \
		bpdocument.obj \
		bpfile.obj \
		calendardocument.obj \
		composer.obj \
		conflictdialog.obj \
		contain.obj \
		datetime.obj \
		docdevicesize.obj \
		docpagesize.obj \
		docscrollview.obj \
		doctabs.obj \
		document.obj \
		fdfmcdialog.obj \
		fileselector.obj \
		filesystem.obj \
		fuelexportdialog.obj \
		fuelinitdialog.obj \
		fuelmodel.obj \
		fuelwizards.obj \
		globalposition.obj \
		globalsite.obj \
		graphaxle.obj \
		graphbar.obj \
		graph.obj \
		graphlimitsdialog.obj \
		graphline.obj \
		graphmarker.obj \
		guidedialog.obj \
		helpbrowser.obj \
        horizontaldistancedialog.obj \
        humiditydialog.obj \
		module.obj \
		modulesdialog.obj \
		moisscenario.obj \
		newext.obj \
		pagemenudialog.obj \
		parser.obj \
		platform-windows.obj \
		printer.obj \
		property.obj \
		propertydialog.obj \
		randfuel.obj \
		randthread.obj \
		realspinbox.obj \
		requestdialog.obj \
		rundialog.obj \
		rxvar.obj \
		siunits.obj \
		standardwizards.obj \
		sundialog.obj \
		sunview.obj \
		textview.obj \
		textviewdocument.obj \
		toc.obj \
		unitsconverterdialog.obj \
		unitseditdialog.obj \
		varcheckbox.obj \
		wizarddialog.obj \
		xeqapp.obj \
		xeqappparser.obj \
		xeqcalc.obj \
		xeqcalcmask.obj \
		xeqcalcreconfig.obj \
		xeqfile.obj \
		xeqtree.obj \
		xeqtreeparser.obj \
		xeqtreeprint.obj \
		xeqvar.obj \
		xeqvaritem.obj \
		xfblib.obj \
		xmlparser.obj
FORMS =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	moc_aboutdialog.cpp \
		moc_appdialog.cpp \
		moc_appearancedialog.cpp \
		moc_appmessage.cpp \
		moc_appwindow.cpp \
		moc_attachdialog.cpp \
		moc_bpdocument.cpp \
		moc_calendardocument.cpp \
		moc_conflictdialog.cpp \
		moc_document.cpp \
		moc_fdfmcdialog.cpp \
		moc_fileselector.cpp \
		moc_fuelexportdialog.cpp \
		moc_fuelinitdialog.cpp \
		moc_fuelwizards.cpp \
		moc_graphlimitsdialog.cpp \
		moc_guidedialog.cpp \
		moc_helpbrowser.cpp \
        moc_horizontaldistancedialog.cpp \
		moc_humiditydialog.cpp \
		moc_modulesdialog.cpp \
		moc_pagemenudialog.cpp \
		moc_propertydialog.cpp \
		moc_realspinbox.cpp \
		moc_rundialog.cpp \
		moc_standardwizards.cpp \
		moc_sundialog.cpp \
		moc_textviewdocument.cpp \
		moc_textview.cpp \
		moc_unitsconverterdialog.cpp \
		moc_unitseditdialog.cpp \
		moc_varcheckbox.cpp \
		moc_wizarddialog.cpp
OBJMOC	=	moc_aboutdialog.obj \
		moc_appdialog.obj \
		moc_appearancedialog.obj \
		moc_appmessage.obj \
		moc_appwindow.obj \
		moc_attachdialog.obj \
		moc_bpdocument.obj \
		moc_calendardocument.obj \
		moc_conflictdialog.obj \
		moc_document.obj \
		moc_fdfmcdialog.obj \
		moc_fileselector.obj \
		moc_fuelexportdialog.obj \
		moc_fuelinitdialog.obj \
		moc_fuelwizards.obj \
		moc_graphlimitsdialog.obj \
		moc_guidedialog.obj \
		moc_helpbrowser.obj \
        moc_horizontaldistancedialog.obj \
		moc_humiditydialog.obj \
		moc_modulesdialog.obj \
		moc_pagemenudialog.obj \
		moc_propertydialog.obj \
		moc_realspinbox.obj \
		moc_rundialog.obj \
		moc_standardwizards.obj \
		moc_sundialog.obj \
		moc_textviewdocument.obj \
		moc_textview.obj \
		moc_unitsconverterdialog.obj \
		moc_unitseditdialog.obj \
		moc_varcheckbox.obj \
		moc_wizarddialog.obj
DIST	=	
TARGET	=	BehavePlus4.exe

####### Implicit rules

.SUFFIXES: .c .cpp .cc .cxx .C

{.}.cpp{}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fo @<<
	$<
<<

{.}.cc{}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fo @<<
	$<
<<

{.}.cxx{}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fo @<<
	$<
<<

{.}.C{}.obj::
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -Fo @<<
	$<
<<

{.}.c{}.obj::
	$(CC) -c $(CFLAGS) $(INCPATH) -Fo @<<
	$<
<<

####### Build rules

all: qtmakefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC) BehavePlus4.res
	$(LINK) $(LFLAGS) /OUT:$(TARGET) @<< 
	  $(OBJECTS) $(OBJMOC) $(LIBS)
<<


BehavePlus4.res: BehavePlus4.rc
	rc BehavePlus4.rc

mocables: $(SRCMOC)
uicables: $(UICIMPLS) $(UICDECLS)

qtmakefile: BehavePlus4.pro  C:\qt\3.3.3\mkspecs\win32-msvc.net\qmake.conf ..\..\..\..\..\..\qt\3.3.3\lib\qtmain.prl
	$(QMAKE) -o qtmakefile BehavePlus4.pro
qmake: 
	@$(QMAKE) -o qtmakefile BehavePlus4.pro

dist:
	$(ZIP) BehavePlus4.zip $(SOURCES) $(HEADERS) $(DIST) $(FORMS) C:/Documents and Settings/cbevins/software/BehavePlus/v3/src/BehavePlus4.pro ..\..\..\..\..\..\qt\3.3.3\lib\qtmain.prl  

uiclean:
mocclean:
	-$(DEL_FILE) moc_aboutdialog.cpp
	-$(DEL_FILE) moc_appdialog.cpp
	-$(DEL_FILE) moc_appearancedialog.cpp
	-$(DEL_FILE) moc_appmessage.cpp
	-$(DEL_FILE) moc_appwindow.cpp
	-$(DEL_FILE) moc_attachdialog.cpp
	-$(DEL_FILE) moc_bpdocument.cpp
	-$(DEL_FILE) moc_calendardocument.cpp
	-$(DEL_FILE) moc_conflictdialog.cpp
	-$(DEL_FILE) moc_document.cpp
	-$(DEL_FILE) moc_fdfmcdialog.cpp
	-$(DEL_FILE) moc_fileselector.cpp
	-$(DEL_FILE) moc_fuelexportdialog.cpp
	-$(DEL_FILE) moc_fuelinitdialog.cpp
	-$(DEL_FILE) moc_fuelwizards.cpp
	-$(DEL_FILE) moc_graphlimitsdialog.cpp
	-$(DEL_FILE) moc_guidedialog.cpp
	-$(DEL_FILE) moc_helpbrowser.cpp
	-$(DEL_FILE) moc_horizontaldistancedialog.cpp
	-$(DEL_FILE) moc_humiditydialog.cpp
	-$(DEL_FILE) moc_modulesdialog.cpp
	-$(DEL_FILE) moc_pagemenudialog.cpp
	-$(DEL_FILE) moc_propertydialog.cpp
	-$(DEL_FILE) moc_realspinbox.cpp
	-$(DEL_FILE) moc_rundialog.cpp
	-$(DEL_FILE) moc_standardwizards.cpp
	-$(DEL_FILE) moc_sundialog.cpp
	-$(DEL_FILE) moc_textviewdocument.cpp
	-$(DEL_FILE) moc_textview.cpp
	-$(DEL_FILE) moc_unitsconverterdialog.cpp
	-$(DEL_FILE) moc_unitseditdialog.cpp
	-$(DEL_FILE) moc_varcheckbox.cpp
	-$(DEL_FILE) moc_wizarddialog.cpp
	-$(DEL_FILE) moc_aboutdialog.obj
	-$(DEL_FILE) moc_appdialog.obj
	-$(DEL_FILE) moc_appearancedialog.obj
	-$(DEL_FILE) moc_appmessage.obj
	-$(DEL_FILE) moc_appwindow.obj
	-$(DEL_FILE) moc_attachdialog.obj
	-$(DEL_FILE) moc_bpdocument.obj
	-$(DEL_FILE) moc_calendardocument.obj
	-$(DEL_FILE) moc_conflictdialog.obj
	-$(DEL_FILE) moc_document.obj
	-$(DEL_FILE) moc_fdfmcdialog.obj
	-$(DEL_FILE) moc_fileselector.obj
	-$(DEL_FILE) moc_fuelexportdialog.obj
	-$(DEL_FILE) moc_fuelinitdialog.obj
	-$(DEL_FILE) moc_fuelwizards.obj
	-$(DEL_FILE) moc_graphlimitsdialog.obj
	-$(DEL_FILE) moc_guidedialog.obj
	-$(DEL_FILE) moc_helpbrowser.obj
	-$(DEL_FILE) moc_humiditydialog.obj
	-$(DEL_FILE) moc_modulesdialog.obj
	-$(DEL_FILE) moc_pagemenudialog.obj
	-$(DEL_FILE) moc_propertydialog.obj
	-$(DEL_FILE) moc_realspinbox.obj
	-$(DEL_FILE) moc_rundialog.obj
	-$(DEL_FILE) moc_standardwizards.obj
	-$(DEL_FILE) moc_sundialog.obj
	-$(DEL_FILE) moc_textviewdocument.obj
	-$(DEL_FILE) moc_textview.obj
	-$(DEL_FILE) moc_unitsconverterdialog.obj
	-$(DEL_FILE) moc_unitseditdialog.obj
	-$(DEL_FILE) moc_varcheckbox.obj
	-$(DEL_FILE) moc_wizarddialog.obj
clean: uiclean mocclean
	-$(DEL_FILE) cdtlib.obj
	-$(DEL_FILE) aboutdialog.obj
	-$(DEL_FILE) appdialog.obj
	-$(DEL_FILE) appearancedialog.obj
	-$(DEL_FILE) appfilesystem.obj
	-$(DEL_FILE) appmessage.obj
	-$(DEL_FILE) appproperty.obj
	-$(DEL_FILE) appsiunits.obj
	-$(DEL_FILE) apptranslator.obj
	-$(DEL_FILE) appwindow.obj
	-$(DEL_FILE) attachdialog.obj
	-$(DEL_FILE) BehavePlus4.obj
	-$(DEL_FILE) bpcomposecontaindiagram.obj
	-$(DEL_FILE) bpcomposedoc.obj
	-$(DEL_FILE) bpcomposefiredirdiagram.obj
	-$(DEL_FILE) bpcomposefireshapediagram.obj
	-$(DEL_FILE) bpcomposegraphs.obj
	-$(DEL_FILE) bpcomposehaulingchart.obj
	-$(DEL_FILE) bpcomposelogo.obj
	-$(DEL_FILE) bpcomposepage.obj
	-$(DEL_FILE) bpcomposetable1.obj
	-$(DEL_FILE) bpcomposetable2.obj
	-$(DEL_FILE) bpcomposetable3.obj
	-$(DEL_FILE) bpcomposeworksheet.obj
	-$(DEL_FILE) bpdocentry.obj
	-$(DEL_FILE) bpdocument.obj
	-$(DEL_FILE) bpfile.obj
	-$(DEL_FILE) calendardocument.obj
	-$(DEL_FILE) composer.obj
	-$(DEL_FILE) conflictdialog.obj
	-$(DEL_FILE) contain.obj
	-$(DEL_FILE) datetime.obj
	-$(DEL_FILE) docdevicesize.obj
	-$(DEL_FILE) docpagesize.obj
	-$(DEL_FILE) docscrollview.obj
	-$(DEL_FILE) doctabs.obj
	-$(DEL_FILE) document.obj
	-$(DEL_FILE) fdfmcdialog.obj
	-$(DEL_FILE) fileselector.obj
	-$(DEL_FILE) filesystem.obj
	-$(DEL_FILE) fuelexportdialog.obj
	-$(DEL_FILE) fuelinitdialog.obj
	-$(DEL_FILE) fuelmodel.obj
	-$(DEL_FILE) fuelwizards.obj
	-$(DEL_FILE) globalposition.obj
	-$(DEL_FILE) globalsite.obj
	-$(DEL_FILE) graphaxle.obj
	-$(DEL_FILE) graphbar.obj
	-$(DEL_FILE) graph.obj
	-$(DEL_FILE) graphlimitsdialog.obj
	-$(DEL_FILE) graphline.obj
	-$(DEL_FILE) graphmarker.obj
	-$(DEL_FILE) guidedialog.obj
	-$(DEL_FILE) helpbrowser.obj
	-$(DEL_FILE) humiditydialog.obj
	-$(DEL_FILE) module.obj
	-$(DEL_FILE) modulesdialog.obj
	-$(DEL_FILE) moisscenario.obj
	-$(DEL_FILE) newext.obj
	-$(DEL_FILE) pagemenudialog.obj
	-$(DEL_FILE) parser.obj
	-$(DEL_FILE) platform-windows.obj
	-$(DEL_FILE) printer.obj
	-$(DEL_FILE) property.obj
	-$(DEL_FILE) propertydialog.obj
	-$(DEL_FILE) randfuel.obj
	-$(DEL_FILE) randthread.obj
	-$(DEL_FILE) realspinbox.obj
	-$(DEL_FILE) requestdialog.obj
	-$(DEL_FILE) rundialog.obj
	-$(DEL_FILE) rxvar.obj
	-$(DEL_FILE) siunits.obj
	-$(DEL_FILE) standardwizards.obj
	-$(DEL_FILE) sundialog.obj
	-$(DEL_FILE) sunview.obj
	-$(DEL_FILE) textview.obj
	-$(DEL_FILE) textviewdocument.obj
	-$(DEL_FILE) toc.obj
	-$(DEL_FILE) unitsconverterdialog.obj
	-$(DEL_FILE) unitseditdialog.obj
	-$(DEL_FILE) varcheckbox.obj
	-$(DEL_FILE) wizarddialog.obj
	-$(DEL_FILE) xeqapp.obj
	-$(DEL_FILE) xeqappparser.obj
	-$(DEL_FILE) xeqcalc.obj
	-$(DEL_FILE) xeqcalcmask.obj
	-$(DEL_FILE) xeqcalcreconfig.obj
	-$(DEL_FILE) xeqfile.obj
	-$(DEL_FILE) xeqtree.obj
	-$(DEL_FILE) xeqtreeparser.obj
	-$(DEL_FILE) xeqtreeprint.obj
	-$(DEL_FILE) xeqvar.obj
	-$(DEL_FILE) xeqvaritem.obj
	-$(DEL_FILE) xfblib.obj
	-$(DEL_FILE) xmlparser.obj
	-$(DEL_FILE) BehavePlus4.res




FORCE:

distclean: clean
	-$(DEL_FILE) $(TARGET)

####### Compile

cdtlib.obj: cdtlib.c cdtlib.h

aboutdialog.obj: aboutdialog.cpp  \
		aboutdialog.h \
		appmessage.h \
		apptranslator.h \
		appdialog.h \
		

appdialog.obj: appdialog.cpp  \
		appdialog.h \
		appfilesystem.h \
		appmessage.h \
		appproperty.h \
		apptranslator.h \
		appwindow.h \
		helpbrowser.h \
		textview.h \
		filesystem.h \
		xeqfile.h \
		property.h \
		xmlparser.h \
		

appearancedialog.obj: appearancedialog.cpp  \
		appearancedialog.h \
		appdialog.h \
		appproperty.h \
		bpdocument.h \
		propertydialog.h \
		property.h \
		varcheckbox.h \
		xmlparser.h \
		document.h \
		xeqvar.h \
		toc.h \
		xeqcalc.h \
		

appfilesystem.obj: appfilesystem.cpp  \
		filesystem.h \
		xeqfile.h \
		

appmessage.obj: appmessage.cpp  \
		appdialog.h \
		appmessage.h \
		apptranslator.h \
		appwindow.h \
		platform.h \
		textview.h \
		

appproperty.obj: appproperty.cpp  \
		appmessage.h \
		appproperty.h \
		appdialog.h \
		property.h \
		xmlparser.h \
		

appsiunits.obj: appsiunits.cpp  \
		appmessage.h \
		appsiunits.h \
		appdialog.h \
		siunits.h \
		

apptranslator.obj: apptranslator.cpp  \
		appmessage.h \
		apptranslator.h \
		platform.h \
		appdialog.h \
		

appwindow.obj: appwindow.cpp  \
		aboutdialog.h \
		app.h \
		appfilesystem.h \
		appmessage.h \
		appproperty.h \
		apptranslator.h \
		appwindow.h \
		bpdocument.h \
		calendardocument.h \
		cdtlib.h \
		datetime.h \
		docscrollview.h \
		document.h \
		fdfmcdialog.h \
		fileselector.h \
		globalposition.h \
		horizontaldistancedialog.h \
		humiditydialog.h \
		platform.h \
		property.h \
		sundialog.h \
		textviewdocument.h \
		unitsconverterdialog.h \
		unitseditdialog.h \
		xeqapp.h \
		appwindow.xpm \
		appdialog.h \
		filesystem.h \
		xeqfile.h \
		xmlparser.h \
		xeqvar.h \
		toc.h \
		xeqcalc.h \
		module.h \
		

attachdialog.obj: attachdialog.cpp  \
		appmessage.h \
		apptranslator.h \
		attachdialog.h \
		filesystem.h \
		fuelmodel.h \
		moisscenario.h \
		requestdialog.h \
		textview.h \
		appdialog.h \
		xeqfile.h \
		

BehavePlus4.obj: BehavePlus4.cpp  \
		app.h \
		appmessage.h \
		appwindow.h \
		platform.h \
		wildfire.xpm \
		appdialog.h \
		

bpcomposecontaindiagram.obj: bpcomposecontaindiagram.cpp  \
		appmessage.h \
		apptranslator.h \
		bpdocument.h \
		composer.h \
		docdevicesize.h \
		docpagesize.h \
		graph.h \
		property.h \
		xeqcalc.h \
		xeqtree.h \
		xeqvar.h \
		xeqvaritem.h \
		appdialog.h \
		document.h \
		toc.h \
		graphaxle.h \
		graphbar.h \
		graphline.h \
		graphmarker.h \
		xmlparser.h \
		

bpcomposedoc.obj: bpcomposedoc.cpp  \
		apptranslator.h \
		appwindow.h \
		bpdocument.h \
		composer.h \
		docdevicesize.h \
		docpagesize.h \
		parser.h \
		property.h \
		xeqcalc.h \
		xeqtree.h \
		xeqvar.h \
		xeqvaritem.h \
		document.h \
		toc.h \
		xmlparser.h \
		

bpcomposefiredirdiagram.obj: bpcomposefiredirdiagram.cpp  \
		appmessage.h \
		apptranslator.h \
		bpdocument.h \
		composer.h \
		docdevicesize.h \
		docpagesize.h \
		property.h \
		xeqcalc.h \
		xeqtree.h \
		xeqvar.h \
		xeqvaritem.h \
		appdialog.h \
		document.h \
		toc.h \
		xmlparser.h \
		

bpcomposefireshapediagram.obj: bpcomposefireshapediagram.cpp  \
		appmessage.h \
		apptranslator.h \
		bpdocument.h \
		composer.h \
		docdevicesize.h \
		docpagesize.h \
		property.h \
		xeqcalc.h \
		xeqtree.h \
		xeqvar.h \
		xeqvaritem.h \
		appdialog.h \
		document.h \
		toc.h \
		xmlparser.h \
		

bpcomposegraphs.obj: bpcomposegraphs.cpp  \
		appmessage.h \
		apptranslator.h \
		bpdocument.h \
		composer.h \
		docdevicesize.h \
		docpagesize.h \
		docscrollview.h \
		graph.h \
		graphaxle.h \
		graphbar.h \
		graphlimitsdialog.h \
		graphline.h \
		property.h \
		xeqcalc.h \
		xeqtree.h \
		xeqvar.h \
		xeqvaritem.h \
		appdialog.h \
		document.h \
		toc.h \
		graphmarker.h \
		xmlparser.h \
		

bpcomposehaulingchart.obj: bpcomposehaulingchart.cpp  \
		appfilesystem.h \
		appmessage.h \
		appsiunits.h \
		apptranslator.h \
		bpdocument.h \
		composer.h \
		docdevicesize.h \
		docpagesize.h \
		graph.h \
		graphaxle.h \
		graphbar.h \
		graphline.h \
		graphmarker.h \
		property.h \
		xeqtree.h \
		bpcomposehaulingchart2.xpm \
		filesystem.h \
		xeqfile.h \
		appdialog.h \
		siunits.h \
		document.h \
		xeqvar.h \
		toc.h \
		xeqcalc.h \
		xmlparser.h \
		

bpcomposelogo.obj: bpcomposelogo.cpp  \
		bpdocument.h \
		composer.h \
		document.h \
		xeqvar.h \
		toc.h \
		xeqcalc.h \
		

bpcomposepage.obj: bpcomposepage.cpp  \
		appproperty.h \
		apptranslator.h \
		appwindow.h \
		bpdocument.h \
		composer.h \
		docpagesize.h \
		doctabs.h \
		property.h \
		logo036.xpm \
		xmlparser.h \
		document.h \
		xeqvar.h \
		toc.h \
		xeqcalc.h \
		

bpcomposetable1.obj: bpcomposetable1.cpp  \
		appfilesystem.h \
		apptranslator.h \
		appwindow.h \
		bpdocument.h \
		composer.h \
		docdevicesize.h \
		docpagesize.h \
		property.h \
		xeqcalc.h \
		xeqtree.h \
		xeqvar.h \
		xeqvaritem.h \
		filesystem.h \
		xeqfile.h \
		document.h \
		toc.h \
		xmlparser.h \
		

bpcomposetable2.obj: bpcomposetable2.cpp  \
		appfilesystem.h \
		appmessage.h \
		apptranslator.h \
		appwindow.h \
		bpdocument.h \
		composer.h \
		docdevicesize.h \
		docpagesize.h \
		property.h \
		xeqcalc.h \
		xeqtree.h \
		xeqvar.h \
		xeqvaritem.h \
		filesystem.h \
		xeqfile.h \
		appdialog.h \
		document.h \
		toc.h \
		xmlparser.h \
		

bpcomposetable3.obj: bpcomposetable3.cpp  \
		appfilesystem.h \
		appmessage.h \
		apptranslator.h \
		appwindow.h \
		bpdocument.h \
		composer.h \
		docdevicesize.h \
		docpagesize.h \
		property.h \
		xeqcalc.h \
		xeqtree.h \
		xeqvar.h \
		xeqvaritem.h \
		filesystem.h \
		xeqfile.h \
		appdialog.h \
		document.h \
		toc.h \
		xmlparser.h \
		

bpcomposeworksheet.obj: bpcomposeworksheet.cpp  \
		appmessage.h \
		apptranslator.h \
		appwindow.h \
		bpdocentry.h \
		bpdocument.h \
		composer.h \
		docdevicesize.h \
		docpagesize.h \
		property.h \
		rxvar.h \
		xeqapp.h \
		xeqcalc.h \
		xeqtree.h \
		xeqvar.h \
		xeqvaritem.h \
		appdialog.h \
		document.h \
		toc.h \
		xmlparser.h \
		module.h \
		xeqfile.h \
		

bpdocentry.obj: bpdocentry.cpp  \
		bpdocentry.h \
		bpdocument.h \
		document.h \
		xeqvar.h \
		toc.h \
		xeqcalc.h \
		

bpdocument.obj: bpdocument.cpp  \
		appdialog.h \
		appearancedialog.h \
		appfilesystem.h \
		appmessage.h \
		apptranslator.h \
		appwindow.h \
		attachdialog.h \
		bpdocentry.h \
		bpdocument.h \
		composer.h \
		conflictdialog.h \
		docdevicesize.h \
		docpagesize.h \
		docscrollview.h \
		doctabs.h \
		fileselector.h \
		fuelinitdialog.h \
		fuelmodel.h \
		guidedialog.h \
		modulesdialog.h \
		moisscenario.h \
		property.h \
		rundialog.h \
		rxvar.h \
		xeqapp.h \
		xeqcalc.h \
		xeqtree.h \
		xeqvar.h \
		propertydialog.h \
		filesystem.h \
		xeqfile.h \
		textview.h \
		document.h \
		toc.h \
		module.h \
		xmlparser.h \
		xeqvaritem.h \
		

bpfile.obj: bpfile.cpp  \
		appdialog.h \
		appfilesystem.h \
		appmessage.h \
		apptranslator.h \
		appwindow.h \
		bpdocentry.h \
		bpdocument.h \
		docscrollview.h \
		fileselector.h \
		fuelexportdialog.h \
		fuelmodel.h \
		parser.h \
		property.h \
		xeqapp.h \
		xeqcalc.h \
		xeqtree.h \
		xeqvar.h \
		filesystem.h \
		xeqfile.h \
		document.h \
		toc.h \
		xmlparser.h \
		module.h \
		

calendardocument.obj: calendardocument.cpp  \
		appmessage.h \
		apptranslator.h \
		appwindow.h \
		calendardocument.h \
		cdtlib.h \
		composer.h \
		datetime.h \
		docdevicesize.h \
		docpagesize.h \
		doctabs.h \
		globalposition.h \
		property.h \
		logo036.xpm \
		appdialog.h \
		document.h \
		toc.h \
		xmlparser.h \
		

composer.obj: composer.cpp  \
		composer.h \
		graph.h \
		platform.h \
		graphaxle.h \
		graphbar.h \
		graphline.h \
		graphmarker.h \
		

conflictdialog.obj: conflictdialog.cpp  \
		apptranslator.h \
		bpdocument.h \
		conflictdialog.h \
		property.h \
		document.h \
		xeqvar.h \
		toc.h \
		xeqcalc.h \
		appdialog.h \
		xmlparser.h \
		

contain.obj: contain.cpp  \
		appmessage.h \
		contain.h \
		appdialog.h \
		

datetime.obj: datetime.cpp  \
		cdtlib.h \
		datetime.h \
		globalposition.h \
		

docdevicesize.obj: docdevicesize.cpp  \
		docdevicesize.h \
		docpagesize.h \
		

docpagesize.obj: docpagesize.cpp  \
		docpagesize.h \
		

docscrollview.obj: docscrollview.cpp  \
		composer.h \
		docdevicesize.h \
		docpagesize.h \
		docscrollview.h \
		document.h \
		toc.h \
		

doctabs.obj: doctabs.cpp  \
		doctabs.h \
		

document.obj: document.cpp  \
		appfilesystem.h \
		appmessage.h \
		apptranslator.h \
		composer.h \
		docdevicesize.h \
		docpagesize.h \
		docscrollview.h \
		doctabs.h \
		document.h \
		filesystem.h \
		pagemenudialog.h \
		printer.h \
		xeqfile.h \
		appdialog.h \
		toc.h \
		

fdfmcdialog.obj: fdfmcdialog.cpp  \
		appmessage.h \
		apptranslator.h \
		fdfmcdialog.h \
		appdialog.h \
		

fileselector.obj: fileselector.cpp  \
		appfilesystem.h \
		appmessage.h \
		apptranslator.h \
		document.h \
		fileselector.h \
		requestdialog.h \
		textview.h \
		filesystem.h \
		xeqfile.h \
		appdialog.h \
		toc.h \
		

filesystem.obj: filesystem.cpp  \
		appmessage.h \
		apptranslator.h \
		appwindow.h \
		filesystem.h \
		platform.h \
		textview.h \
		appdialog.h \
		xeqfile.h \
		

fuelexportdialog.obj: fuelexportdialog.cpp  \
		appmessage.h \
		apptranslator.h \
		bpdocument.h \
		fuelmodel.h \
		fuelexportdialog.h \
		textview.h \
		xeqapp.h \
		xeqtree.h \
		xeqvar.h \
		xeqvaritem.h \
		appdialog.h \
		document.h \
		toc.h \
		xeqcalc.h \
		module.h \
		xeqfile.h \
		

fuelinitdialog.obj: fuelinitdialog.cpp  \
		appmessage.h \
		apptranslator.h \
		bpdocument.h \
		fuelinitdialog.h \
		fuelmodel.h \
		textview.h \
		xeqapp.h \
		xeqvar.h \
		xeqvaritem.h \
		appdialog.h \
		document.h \
		toc.h \
		xeqcalc.h \
		module.h \
		xeqfile.h \
		

fuelmodel.obj: fuelmodel.cpp  \
		appmessage.h \
		appsiunits.h \
		apptranslator.h \
		fuelmodel.h \
		appdialog.h \
		siunits.h \
		

fuelwizards.obj: fuelwizards.cpp  \
		appsiunits.h \
		apptranslator.h \
		fuelwizards.h \
		xeqvar.h \
		siunits.h \
		wizarddialog.h \
		appdialog.h \
		xeqcalc.h \
		

globalposition.obj: globalposition.cpp  \
		globalposition.h \
		

globalsite.obj: globalsite.cpp  \
		globalsite.h \
		globalposition.h \
		

graphaxle.obj: graphaxle.cpp  \
		graphaxle.h \
		

graphbar.obj: graphbar.cpp  \
		graphbar.h \
		

graph.obj: graph.cpp  \
		appmessage.h \
		graph.h \
		graphaxle.h \
		graphbar.h \
		graphline.h \
		graphmarker.h \
		appdialog.h \
		

graphlimitsdialog.obj: graphlimitsdialog.cpp  \
		appmessage.h \
		apptranslator.h \
		bpdocument.h \
		graph.h \
		graphlimitsdialog.h \
		property.h \
		realspinbox.h \
		xeqtree.h \
		xeqvar.h \
		appdialog.h \
		document.h \
		toc.h \
		xeqcalc.h \
		graphaxle.h \
		graphbar.h \
		graphline.h \
		graphmarker.h \
		xmlparser.h \
		

graphline.obj: graphline.cpp  \
		appmessage.h \
		graphline.h \
		appdialog.h \
		

graphmarker.obj: graphmarker.cpp  \
		graphmarker.h \
		

guidedialog.obj: guidedialog.cpp  \
		appmessage.h \
		apptranslator.h \
		bpdocument.h \
		fuelmodel.h \
		fuelwizards.h \
		guidedialog.h \
		moisscenario.h \
		standardwizards.h \
		textview.h \
		xeqapp.h \
		xeqtree.h \
		xeqvar.h \
		xeqvaritem.h \
		appdialog.h \
		document.h \
		toc.h \
		xeqcalc.h \
		wizarddialog.h \
		module.h \
		xeqfile.h \
		

helpbrowser.obj: helpbrowser.cpp  \
		appmessage.h \
		apptranslator.h \
		helpbrowser.h \
		platform.h \
		textview.h \
		appdialog.h \


horizontaldistancedialog.obj : horizontaldistancedialog.cpp \
			appmessage.h \
			appdialog.h \
			appsiunits.h \
			siunits.h \
			apptranslator.h \
			horizontaldistancedialog.h


humiditydialog.obj : humiditydialog.cpp \
			appmessage.h \
			appdialog.h \
			appsiunits.h \
			siunits.h \
			apptranslator.h \
			humiditydialog.h \
			xfblib.h \
			newext.h \
			randfuel.h \
			randthread.h

module.obj: module.cpp  \
		module.h \
		

modulesdialog.obj: modulesdialog.cpp  \
		appmessage.h \
		apptranslator.h \
		appwindow.h \
		bpdocument.h \
		module.h \
		modulesdialog.h \
		propertydialog.h \
		property.h \
		varcheckbox.h \
		xeqapp.h \
		appdialog.h \
		document.h \
		xeqvar.h \
		toc.h \
		xeqcalc.h \
		xmlparser.h \
		xeqfile.h \
		

moisscenario.obj: moisscenario.cpp  \
		appmessage.h \
		appsiunits.h \
		apptranslator.h \
		moisscenario.h \
		appdialog.h \
		siunits.h \
		

newext.obj: newext.cpp  \
		newext.h \
		randfuel.h \
		randthread.h \
		

pagemenudialog.obj: pagemenudialog.cpp  \
		apptranslator.h \
		document.h \
		pagemenudialog.h \
		toc.h \
		appdialog.h \
		

parser.obj: parser.cpp  \
		appmessage.h \
		parser.h \
		appdialog.h \
		

platform-windows.obj: platform-windows.cpp  \
		appfilesystem.h \
		appmessage.h \
		platform.h \
		filesystem.h \
		xeqfile.h \
		appdialog.h \
		

printer.obj: printer.cpp  \
		printer.h \
		

property.obj: property.cpp  \
		appmessage.h \
		apptranslator.h \
		property.h \
		appdialog.h \
		xmlparser.h \
		

propertydialog.obj: propertydialog.cpp  \
		appmessage.h \
		apptranslator.h \
		appwindow.h \
		propertydialog.h \
		property.h \
		varcheckbox.h \
		appdialog.h \
		xmlparser.h \
		

randfuel.obj: randfuel.cpp  \
		randfuel.h \
		newext.h \
		randthread.h \
		

randthread.obj: randthread.cpp  \
		randthread.h \
		

realspinbox.obj: realspinbox.cpp  \
		realspinbox.h \
		

requestdialog.obj: requestdialog.cpp  \
		requestdialog.h \
		appdialog.h \
		

rundialog.obj: rundialog.cpp  \
		appmessage.h \
		apptranslator.h \
		bpdocument.h \
		property.h \
		rundialog.h \
		textview.h \
		xeqtree.h \
		xeqvar.h \
		appdialog.h \
		document.h \
		toc.h \
		xeqcalc.h \
		xmlparser.h \
		

rxvar.obj: rxvar.cpp  \
		appmessage.h \
		appsiunits.h \
		apptranslator.h \
		parser.h \
		rxvar.h \
		appdialog.h \
		siunits.h \
		xeqvar.h \
		xeqvaritem.h \
		xeqcalc.h \
		

siunits.obj: siunits.cpp  \
		appmessage.h \
		siunits.h \
		appdialog.h \
		

standardwizards.obj: standardwizards.cpp  \
		appsiunits.h \
		apptranslator.h \
		fuelmodel.h \
		property.h \
		standardwizards.h \
		xeqapp.h \
		xeqcalc.h \
		xeqtree.h \
		xeqvar.h \
		bpdocument.h \
		parser.h \
		siunits.h \
		xmlparser.h \
		wizarddialog.h \
		appdialog.h \
		module.h \
		xeqfile.h \
		document.h \
		toc.h \
		

sundialog.obj: sundialog.cpp  \
		appfilesystem.h \
		appmessage.h \
		apptranslator.h \
		datetime.h \
		globalposition.h \
		property.h \
		sundialog.h \
		textview.h \
		filesystem.h \
		xeqfile.h \
		appdialog.h \
		xmlparser.h \
		

sunview.obj: sunview.cpp  \
		cdtlib.h \
		sunview.h \
		datetime.h \
		globalsite.h \
		globalposition.h \
		

textview.obj: textview.cpp  \
		appmessage.h \
		apptranslator.h \
		appwindow.h \
		printer.h \
		textview.h \
		appdialog.h \
		

textviewdocument.obj: textviewdocument.cpp  \
		appmessage.h \
		apptranslator.h \
		textviewdocument.h \
		appdialog.h \
		document.h \
		toc.h \
		

toc.obj: toc.cpp  \
		toc.h \
		toc.xpm \
		

unitsconverterdialog.obj: unitsconverterdialog.cpp  \
		appmessage.h \
		appsiunits.h \
		apptranslator.h \
		unitsconverterdialog.h \
		appdialog.h \
		siunits.h \
		

unitseditdialog.obj: unitseditdialog.cpp  \
		appmessage.h \
		appsiunits.h \
		apptranslator.h \
		appwindow.h \
		bpdocument.h \
		unitseditdialog.h \
		xeqtree.h \
		xeqvar.h \
		appdialog.h \
		siunits.h \
		document.h \
		toc.h \
		xeqcalc.h \
		

varcheckbox.obj: varcheckbox.cpp  \
		helpbrowser.h \
		varcheckbox.h \
		

wizarddialog.obj: wizarddialog.cpp  \
		apptranslator.h \
		bpdocument.h \
		textview.h \
		wizarddialog.h \
		xeqvar.h \
		document.h \
		toc.h \
		xeqcalc.h \
		appdialog.h \
		

xeqapp.obj: xeqapp.cpp  \
		appmessage.h \
		appproperty.h \
		appsiunits.h \
		apptranslator.h \
		fuelmodel.h \
		module.h \
		moisscenario.h \
		xeqapp.h \
		xeqappparser.h \
		xeqfile.h \
		xeqtree.h \
		xeqvar.h \
		xeqvaritem.h \
		appdialog.h \
		property.h \
		xmlparser.h \
		siunits.h \
		xeqcalc.h \
		

xeqappparser.obj: xeqappparser.cpp  \
		appmessage.h \
		appproperty.h \
		apptranslator.h \
		xeqapp.h \
		xeqappparser.h \
		xeqvar.h \
		xeqvaritem.h \
		appdialog.h \
		property.h \
		xmlparser.h \
		module.h \
		xeqfile.h \
		xeqcalc.h \
		

xeqcalc.obj: xeqcalc.cpp  \
		appmessage.h \
		appsiunits.h \
		apptranslator.h \
		bpdocument.h \
		cdtlib.h \
		contain.h \
		fuelmodel.h \
		moisscenario.h \
		parser.h \
		property.h \
		xeqcalc.h \
		xeqvar.h \
		xeqtree.h \
		xfblib.h \
		appdialog.h \
		siunits.h \
		document.h \
		toc.h \
		xmlparser.h \
		newext.h \
		randfuel.h \
		randthread.h \
		

xeqcalcmask.obj: xeqcalcmask.cpp  \
		appmessage.h \
		apptranslator.h \
		fuelmodel.h \
		parser.h \
		property.h \
		xeqcalc.h \
		xeqtree.h \
		xeqvar.h \
		appdialog.h \
		xmlparser.h \
		

xeqcalcreconfig.obj: xeqcalcreconfig.cpp  \
		property.h \
		xeqcalc.h \
		xeqtree.h \
		xeqvar.h \
		xmlparser.h \
		

xeqfile.obj: xeqfile.cpp  \
		xeqfile.h \
		

xeqtree.obj: xeqtree.cpp  \
		appmessage.h \
		appproperty.h \
		appsiunits.h \
		apptranslator.h \
		appwindow.h \
		filesystem.h \
		fuelmodel.h \
		moisscenario.h \
		parser.h \
		property.h \
		rxvar.h \
		xeqapp.h \
		xeqcalc.h \
		xeqtree.h \
		xeqtreeparser.h \
		xeqvar.h \
		xeqvaritem.h \
		appdialog.h \
		xmlparser.h \
		siunits.h \
		xeqfile.h \
		module.h \
		

xeqtreeparser.obj: xeqtreeparser.cpp  \
		appmessage.h \
		appsiunits.h \
		apptranslator.h \
		property.h \
		rxvar.h \
		xeqtree.h \
		xeqtreeparser.h \
		xeqvar.h \
		appdialog.h \
		siunits.h \
		xmlparser.h \
		xeqvaritem.h \
		xeqcalc.h \
		

xeqtreeprint.obj: xeqtreeprint.cpp  \
		appmessage.h \
		apptranslator.h \
		appwindow.h \
		module.h \
		property.h \
		xeqapp.h \
		xeqtree.h \
		xeqvar.h \
		xeqvaritem.h \
		appdialog.h \
		xmlparser.h \
		xeqfile.h \
		xeqcalc.h \
		

xeqvar.obj: xeqvar.cpp  \
		appmessage.h \
		appsiunits.h \
		apptranslator.h \
		parser.h \
		xeqvar.h \
		xeqvaritem.h \
		appdialog.h \
		siunits.h \
		xeqcalc.h \
		

xeqvaritem.obj: xeqvaritem.cpp  \
		appmessage.h \
		xeqvaritem.h \
		appdialog.h \
		

xfblib.obj: xfblib.cpp  \
		xfblib.h \
		newext.h \
		randfuel.h \
		randthread.h \
		

xmlparser.obj: xmlparser.cpp  \
		appmessage.h \
		apptranslator.h \
		xmlparser.h \
		appdialog.h \
		

moc_aboutdialog.obj: moc_aboutdialog.cpp  aboutdialog.h appdialog.h

moc_appdialog.obj: moc_appdialog.cpp  appdialog.h 

moc_appearancedialog.obj: moc_appearancedialog.cpp  appearancedialog.h propertydialog.h \
		appdialog.h

moc_appmessage.obj: moc_appmessage.cpp  appmessage.h appdialog.h

moc_appwindow.obj: moc_appwindow.cpp  appwindow.h 

moc_attachdialog.obj: moc_attachdialog.cpp  attachdialog.h appdialog.h \
		textview.h

moc_bpdocument.obj: moc_bpdocument.cpp  bpdocument.h document.h \
		xeqvar.h \
		toc.h \
		xeqcalc.h

moc_calendardocument.obj: moc_calendardocument.cpp  calendardocument.h document.h \
		toc.h

moc_conflictdialog.obj: moc_conflictdialog.cpp  conflictdialog.h appdialog.h

moc_document.obj: moc_document.cpp  document.h toc.h

moc_fdfmcdialog.obj: moc_fdfmcdialog.cpp  fdfmcdialog.h appdialog.h

moc_fileselector.obj: moc_fileselector.cpp  fileselector.h appdialog.h

moc_fuelexportdialog.obj: moc_fuelexportdialog.cpp  fuelexportdialog.h appdialog.h

moc_fuelinitdialog.obj: moc_fuelinitdialog.cpp  fuelinitdialog.h appdialog.h

moc_fuelwizards.obj: moc_fuelwizards.cpp  fuelwizards.h wizarddialog.h \
		appdialog.h

moc_graphlimitsdialog.obj: moc_graphlimitsdialog.cpp  graphlimitsdialog.h appdialog.h \
		graphaxle.h

moc_guidedialog.obj: moc_guidedialog.cpp  guidedialog.h appdialog.h

moc_helpbrowser.obj: moc_helpbrowser.cpp  helpbrowser.h 

moc_horizontaldistancedialog.obj : moc_horizontaldistancedialog.cpp

moc_humiditydialog.obj : moc_humiditydialog.cpp

moc_modulesdialog.obj: moc_modulesdialog.cpp  modulesdialog.h appdialog.h \
		module.h

moc_pagemenudialog.obj: moc_pagemenudialog.cpp  pagemenudialog.h appdialog.h

moc_propertydialog.obj: moc_propertydialog.cpp  propertydialog.h appdialog.h

moc_realspinbox.obj: moc_realspinbox.cpp  realspinbox.h 

moc_rundialog.obj: moc_rundialog.cpp  rundialog.h appdialog.h

moc_standardwizards.obj: moc_standardwizards.cpp  standardwizards.h wizarddialog.h \
		appdialog.h

moc_sundialog.obj: moc_sundialog.cpp  sundialog.h appdialog.h

moc_textviewdocument.obj: moc_textviewdocument.cpp  textviewdocument.h document.h \
		toc.h

moc_textview.obj: moc_textview.cpp  textview.h 

moc_unitsconverterdialog.obj: moc_unitsconverterdialog.cpp  unitsconverterdialog.h appdialog.h

moc_unitseditdialog.obj: moc_unitseditdialog.cpp  unitseditdialog.h appdialog.h

moc_varcheckbox.obj: moc_varcheckbox.cpp  varcheckbox.h 

moc_wizarddialog.obj: moc_wizarddialog.cpp  wizarddialog.h appdialog.h

moc_aboutdialog.cpp: $(MOC) aboutdialog.h
	$(MOC) aboutdialog.h -o moc_aboutdialog.cpp

moc_appdialog.cpp: $(MOC) appdialog.h
	$(MOC) appdialog.h -o moc_appdialog.cpp

moc_appearancedialog.cpp: $(MOC) appearancedialog.h
	$(MOC) appearancedialog.h -o moc_appearancedialog.cpp

moc_appmessage.cpp: $(MOC) appmessage.h
	$(MOC) appmessage.h -o moc_appmessage.cpp

moc_appwindow.cpp: $(MOC) appwindow.h
	$(MOC) appwindow.h -o moc_appwindow.cpp

moc_attachdialog.cpp: $(MOC) attachdialog.h
	$(MOC) attachdialog.h -o moc_attachdialog.cpp

moc_bpdocument.cpp: $(MOC) bpdocument.h
	$(MOC) bpdocument.h -o moc_bpdocument.cpp

moc_calendardocument.cpp: $(MOC) calendardocument.h
	$(MOC) calendardocument.h -o moc_calendardocument.cpp

moc_conflictdialog.cpp: $(MOC) conflictdialog.h
	$(MOC) conflictdialog.h -o moc_conflictdialog.cpp

moc_document.cpp: $(MOC) document.h
	$(MOC) document.h -o moc_document.cpp

moc_fdfmcdialog.cpp: $(MOC) fdfmcdialog.h
	$(MOC) fdfmcdialog.h -o moc_fdfmcdialog.cpp

moc_fileselector.cpp: $(MOC) fileselector.h
	$(MOC) fileselector.h -o moc_fileselector.cpp

moc_fuelexportdialog.cpp: $(MOC) fuelexportdialog.h
	$(MOC) fuelexportdialog.h -o moc_fuelexportdialog.cpp

moc_fuelinitdialog.cpp: $(MOC) fuelinitdialog.h
	$(MOC) fuelinitdialog.h -o moc_fuelinitdialog.cpp

moc_fuelwizards.cpp: $(MOC) fuelwizards.h
	$(MOC) fuelwizards.h -o moc_fuelwizards.cpp

moc_graphlimitsdialog.cpp: $(MOC) graphlimitsdialog.h
	$(MOC) graphlimitsdialog.h -o moc_graphlimitsdialog.cpp

moc_guidedialog.cpp: $(MOC) guidedialog.h
	$(MOC) guidedialog.h -o moc_guidedialog.cpp

moc_helpbrowser.cpp: $(MOC) helpbrowser.h
	$(MOC) helpbrowser.h -o moc_helpbrowser.cpp

moc_horizontaldistancedialog.cpp : horizontaldistancedialog.h
		$(MOC) horizontaldistancedialog.h -o moc_horizontaldistancedialog.cpp

moc_humiditydialog.cpp : humiditydialog.h
		$(MOC) humiditydialog.h -o moc_humiditydialog.cpp

moc_modulesdialog.cpp: $(MOC) modulesdialog.h
	$(MOC) modulesdialog.h -o moc_modulesdialog.cpp

moc_pagemenudialog.cpp: $(MOC) pagemenudialog.h
	$(MOC) pagemenudialog.h -o moc_pagemenudialog.cpp

moc_propertydialog.cpp: $(MOC) propertydialog.h
	$(MOC) propertydialog.h -o moc_propertydialog.cpp

moc_realspinbox.cpp: $(MOC) realspinbox.h
	$(MOC) realspinbox.h -o moc_realspinbox.cpp

moc_rundialog.cpp: $(MOC) rundialog.h
	$(MOC) rundialog.h -o moc_rundialog.cpp

moc_standardwizards.cpp: $(MOC) standardwizards.h
	$(MOC) standardwizards.h -o moc_standardwizards.cpp

moc_sundialog.cpp: $(MOC) sundialog.h
	$(MOC) sundialog.h -o moc_sundialog.cpp

moc_textviewdocument.cpp: $(MOC) textviewdocument.h
	$(MOC) textviewdocument.h -o moc_textviewdocument.cpp

moc_textview.cpp: $(MOC) textview.h
	$(MOC) textview.h -o moc_textview.cpp

moc_unitsconverterdialog.cpp: $(MOC) unitsconverterdialog.h
	$(MOC) unitsconverterdialog.h -o moc_unitsconverterdialog.cpp

moc_unitseditdialog.cpp: $(MOC) unitseditdialog.h
	$(MOC) unitseditdialog.h -o moc_unitseditdialog.cpp

moc_varcheckbox.cpp: $(MOC) varcheckbox.h
	$(MOC) varcheckbox.h -o moc_varcheckbox.cpp

moc_wizarddialog.cpp: $(MOC) wizarddialog.h
	$(MOC) wizarddialog.h -o moc_wizarddialog.cpp

####### Install

install:  

uninstall:  

